### ISSUE TITLE
缺少pickle数据文件 __chinese_pinyin, __chinese_wubi 和 __wubi_chinese

### ISSUE THREAD

**Issue by Jerryzhao-z** [arcsecw/chinese_wubi#1]
用测试文件跑了一下发现缺少确少了题目中的几个数据文件。
`
 python w_trans.py --input test.txt --output result.txt --type 0

init __chinese_wubi dict ...
Traceback (most recent call last):
  File "w_trans.py", line 135, in <module>
    main()
  File "w_trans.py", line 130, in main
    outfile = map[args.type](args.input,args.output)
  File "w_trans.py", line 104, in chinese_wubi
    self.__check_prepare(infile, type)
  File "w_trans.py", line 34, in __check_prepare
    self.__dict[type] = cPickle.load(open(type, 'r'))
IOError: [Errno 2] No such file or directory: '__chinese_wubi'
`

**Comment by arcsecw** [comment]
好，我修改下
