### ISSUE TITLE
如何一次转整个文档

### ISSUE THREAD

**Issue by happygirl123456** [arcsecw/chinese_wubi#6]
print wubi.get('WenChaoWang爱自由','cw')
只能这样一句话一句话的转吗，想一次转整个文档，怎样做，谢谢？

**Comment by arcsecw** [comment]
是linux or mac的话试试下面的命令

`tr "\n" "##" < test.txt |xargs wubi -t cw -c | tr "##" "\n" > result.txt`
命令讲解
1 tr "\n" "##" < test.txt 将test.txt 中的所有换行替换为##（因为命令行模式传参数不能遇到换行）
2 |xargs wubi -t cw -c  【|】linux管道，将第一步的输出作为-c参数的输入
3 | tr "##" "\n" 【|】linux管道，将第二步的输出作为tr命令的输入，实现将##重新替换为换行
4 |> result.txt` 【|】linux管道， 将第三步的输出写入到result.txt文件中 （>一个大于号是清空原有文件内容并写入，>>两个大于号是追加写）

**Comment by happygirl123456** [comment]
您好，我是在linux平台上，我用您上面提到的命令想将一个文本转为五笔字形码，但是得到的result.txt中没有写入任何东西，是什么原因呢？

**Comment by happygirl123456** [comment]
1、
将 由 开发署 政策 和 程序 规定 的 方案 编制 安排 和 指导方针 作为 战略 框架 方案 管理 、 监测 和 评价 的 指导 。
向 机构 效率 和 实效 产出 分配资源
此外 , 工作人员 和 管理人员 愿意 提出 与 道德 相关 的 问题 并 寻求 关于 道德 标准 和 行为 的 指导 也 推动 增加 了 服务 请求 的 数量 。
文本中的内容是上面这样，出现
usage: wubi [-h] [-t T] [-c C]
wubi: error: unrecognized arguments: 由 开发署 政策 和 程序 规定 的 方案 编制 安排 和 指导方针 作为 战略 框架 方案 管理 、 监测 和 评价 的 指导 。#向 机构 效率 和 实效 产出 分配资源#此外 , 工作人员 和 管理人员 愿意 提出 与 道德 相关 的 问题 并 寻求 关于 道德 标准 和 行为 的 指导 也 推动 增加 了 服务 请求 的 数量 。#
这样的错误
2、
'将 由 开发署 政策 和 程序 规定 的 方案 编制 安排 和 指导方针 作为 战略 框架 方案 管理 、 监测 和 评价 的 指导 。
向 机构 效率 和 实效 产出 分配资源
此外 , 工作人员 和 管理人员 愿意 提出 与 道德 相关 的 问题 并 寻求 关于 道德 标准 和 行为 的 指导 也 推动 增加 了 服务 请求 的 数量 。'
文本内容是以上这样，前后加了单引号，出现
Traceback (most recent call last):
  File "/usr/bin/wubi", line 11, in <module>
    sys.exit(wubi())
  File "/usr/lib/python2.7/site-packages/wubi/cmd.py", line 19, in wubi
    print(get(u(args.c),args.t))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u3001' in position 119: ordinal not in range(128)
这样的错误。

是什么原因，如何解决呢，谢谢！

**Comment by arcsecw** [comment]
因为命令行模式传参数不能遇到换行
